### ISSUE TITLE
TypeError on `npm run dev` after installing `@logtail/next`

### ISSUE THREAD

**Issue by davit-b** [logtail/logtail-nextjs#4]
```
$ npm run dev                                                                                  11:07:31 AM

> vercel-base@0.1.0 dev
> next dev -p 4000

ready - started server on 0.0.0.0:4000, url: http://localhost:4000
info  - Loaded env from /Users/davitbalagyozyan/workplace/nextjs/better-you/.env
TypeError: Cannot read properties of undefined (reading 'host')
    at GenericConfig.getHeaderOrDefault (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/platform/generic.js:69:27)
    at GenericConfig.generateRequestMeta (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/platform/generic.js:61:24)
    at /Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:162:47
    at step (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:44:23)
    at Object.next (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:25:53)
    at /Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:15:12)
    at /Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/@logtail/next/dist/withLogtail.js:157:41
    at Object.normalizeConfig (/Users/davitbalagyozyan/workplace/nextjs/better-you/node_modules/next/dist/server/config-shared.js:123:18) {
  type: 'TypeError'
}
```

This was due to the way that I wrapped the `withLogTail` plugin with another plugin in the next.config being incorrect.

The correct way to do it was to use `withPlugins` and then it works
`module.exports = withPlugins([nextEnv(), withLogtail()], nextConfig)`

If you guys document users to use the next plugins for logtail then atleast mention in the docs somewhere that using it with additional plugins requires some extra work.

**Comment by davit-b** [comment]
Actually, it looks like this issue is happening in the vercel buildset

```


Cloning completed: 765.039ms
--
12:46:35.260 | Restored build cache
12:46:35.307 | Running "vercel build"
12:46:36.005 | Vercel CLI 31.0.1
12:46:36.506 | Installing dependencies...
12:46:36.894 | yarn install v1.22.17
12:46:36.938 | info No lockfile found.
12:46:36.948 | [1/4] Resolving packages...
12:46:49.323 | warning sst > aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
12:46:49.342 | warning sst > aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
12:46:51.736 | [2/4] Fetching packages...
12:48:00.246 | [3/4] Linking dependencies...
12:48:00.250 | warning " > @xstate/inspect@0.8.0" has unmet peer dependency "ws@^8.0.0".
12:48:00.255 | warning "jotai-devtools > @redux-devtools/extension@3.2.5" has unmet peer dependency "redux@^3.1.0 \|\| ^4.0.0".
12:48:00.257 | warning " > react-type-animation@3.1.0" has unmet peer dependency "prop-types@^15.5.4".
12:48:56.042 | [4/4] Building fresh packages...
12:48:56.525 | success Saved lockfile.
12:48:56.531 | Done in 139.64s.
12:48:56.614 | Detected Next.js version: 13.3.0
12:48:56.616 | Running "yarn run build"
12:48:56.879 | yarn run v1.22.17
12:48:56.925 | $ next build
12:48:57.471 | unhandledRejection TypeError: Cannot read properties of undefined (reading 'host')
12:48:57.471 | at /vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:244:43
12:48:57.471 | at step (/vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:44:23)
12:48:57.471 | at Object.next (/vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:25:53)
12:48:57.472 | at /vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:19:71
12:48:57.472 | at new Promise (<anonymous>)
12:48:57.472 | at __awaiter (/vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:15:12)
12:48:57.472 | at /vercel/path0/node_modules/@logtail/next/dist/withLogtail.js:234:40
12:48:57.472 | at /vercel/path0/node_modules/next-compose-plugins/lib/compose.js:100:23
12:48:57.472 | at Array.forEach (<anonymous>)
12:48:57.473 | at composePlugins (/vercel/path0/node_modules/next-compose-plugins/lib/compose.js:77:11)
12:48:57.492 | error Command failed with exit code 1.
12:48:57.492 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:48:57.518 | Error: Command "yarn run build" exited with 1
```

even though my `next.config.js` is configured with 
```
  typescript: {
    // !! WARN !!
    // Dangerously allow production builds to successfully complete even if
    // your project has type errors.
    // !! WARN !!
    ignoreBuildErrors: true,
  },
  ```
  
  this issue is still blocking the build.

**Comment by davit-b** [comment]
hm https://github.com/logtail/logtail-nextjs/blob/a463432f28dfd7d4339ec236e6d47c691fb8e4da/src/withLogtail.ts#L173

**Comment by curusarn** [comment]
Hi @davit-b,

Thanks for raising the issue.

I'm passing it on to the team to investigate.  
We'll report back one we know more.

Thanks for bringing this to our attention.

**Comment by PetrHeinz** [comment]
Hello @davit-b,

I've tried to approximate your build with clean install of Next.js 13, `@logtail/next`, `next-env` and `next-compose-plugins`, which you can find here: https://github.com/PetrHeinz/vercel-demo2/commits/main.

The first argument of `withPlugins` should be array of `function(param: NextConfig): NextConfig`. In the example provided above, `withLogtail` is called immediately instead of passed into `withPlugins`. This change should help:

```diff
- module.exports = withPlugins([nextEnv(), withLogtail()], nextConfig)
+ module.exports = withPlugins([nextEnv(), withLogtail], nextConfig)
```

---

It's quite easy to miss since `nextEnv` is being called. In the [Next-env usage documentation](https://github.com/formatlos/next-env#usage), they're recommending to extract the result of `nextEnv()` into `withNextEnv`:

```js
const nextEnv = require('next-env');
const dotenvLoad = require('dotenv-load');

dotenvLoad();

const withNextEnv = nextEnv();

module.exports = withNextEnv({
  // Your Next.js config.
});
```

```diff
- module.exports = withPlugins([nextEnv(), withLogtail()], nextConfig)
+ const withNextEnv = nextEnv()
+
+ module.exports = withPlugins([withNextEnv, withLogtail], nextConfig)
```

---

Hope that helps! Please, let me know so I can close this issue 🙂

**Comment by PetrHeinz** [comment]
Hi @davit-b, I'm closing this issue as resolved. Hope the solution I've provided works for you 🙂
